### ISSUE TITLE
Error when you type space only

### ISSUE THREAD

**Issue by kezaweb** [terwey/ng-aloha-editor#6] opened 2014-05-23 16:09 UTC
I have this error when I type space only... 

TypeError: jQueryEvent.target.activeEditable is null

l.192 of ng-aloha-editor.js
    if (jQueryEvent.target.activeEditable.originalObj[0].id == elem.attr('id')) {

You can reproduce on your demo http://terwey.github.io/ng-aloha-editor/ with firefox ( on MacOS / or Linux )

Thanks you ;-)

Yoann

**Comment by terwey** [comment] 2014-05-23 17:40
@kezaweb thanks for reporting, I will take a look next monday :)

To be sure, the steps to reproduce are:
1) fill in a SPACE only in the Aloha element

**Comment by kezaweb** [comment] 2014-05-25 13:56
I can give you some details about the problem :
When I type one space, I haven't got this error... but when I type two spaces... I got it... 

I hope that it can help you ;-)

Thank you !

Yoann

**Comment by terwey** [comment] 2014-09-30 17:36
@plamut hey can you maybe take a look if this bug is still actual?

**Comment by plamut** [comment] 2014-09-30 19:33
I think this has been fixed in the pull request I sent. I basically added checks if _jQueryEvent.target.activeEditable_ is null.

I can check again next  week, though, when I come back home.

**Comment by plamut** [comment] 2014-10-07 11:21
Update: just did a quick test in Chromium and I was not able to reproduce the bug by typing spaces into an (empty) field.

**Comment by terwey** [comment] 2014-10-07 11:36
@plamut the bug (as reported) only happened in Firefox :)

**Comment by plamut** [comment] 2014-10-07 11:43
Oh ... of course. :)

Well, it works there, too (at least for me). Also tried on your demo, cleared the field, typed in some spaces, all good.
(the fix I sent the last time has already been merged into the demo, right?)

**Comment by terwey** [comment] 2014-10-07 12:18
It wasn't updated yet, but it is now. I also can't reproduce anymore. @kezaweb closing this as it seems to be fixed. Feel free to re-open if you can reproduce.
(If you use the Live demo, be sure to refresh your Javascript cache)

**Closed as completed by terwey** 2014-10-07 12:18 UTC
